Drop deprecated pkg_resources
pace-neutrons/Euphonic pull request #287
Opened 2023-09-01 17:31 UTC by ajjackson

This line was causing some deprecation warnings. I think this is the right way to modernise it?

2023-09-01 18:56 UTC, ajjackson commented
Oldlibs is failing, presumably there is a (Matplotlib?) version that doesn't like the Path objects and expects a string.

Could convert to string but then it will stay that way forever: tempted to narrow down the problematic version and apply tweak in that case only. Then it is more likely to be cleaned up later...

2023-09-04 09:16 UTC, ajjackson commented
After a bit of binary search, Matplotlib styles support Path objects from version 3.2 (March 2020). It doesn't seem unreasonable to bump the minimum requirement to this.

(Mantid is currently pinned to version 3.6)

2023-09-04 09:59 UTC, ajjackson commented
@oerc0122 @mducle Is there any reason to be concerned about bumping the Matplotlib dependency a bit? It's nice to do things with Path objects where possible :smile:

2023-09-04 10:12 UTC, oerc0122 requested changes
Just a typo here.

Don't think there should be any concern about bumping.

2023-09-04 10:12 UTC, oerc0122 commented on CHANGELOG.rst
> +  - Minium version of matplotlib increased from 2.2.2 to 3.2.0
Minimum

2023-09-04 10:16 UTC, mducle commented
I don't think so, I think we just use fairly standard Matplotlib methods which haven't changed between version 2 and 3.

2023-09-04 10:21 UTC, ajjackson commented
Great, thanks :-) Will merge when tests pass again.

2023-09-04 10:22 UTC, oerc0122 commented
Having taken a look at the docs, the main difference is that you no longer have Python 2 support (which I don't think is an issue at this point) and unless you're mucking around in the backend, the interfaces are much the same for standard calls.

2023-09-04 10:22 UTC, oerc0122 approved these changes

2023-09-04 10:56 UTC, merged